### ISSUE TITLE
Error 400, redirect_uri_mismatch

### ISSUE THREAD

**Issue by Monsieux** [rapidwebltd/php-google-people-api#13]
Lads, thanks for this fantastic project. Its the first time I'm implementing a solution using OAuth2.

At this moment I receive an error which is:

> The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type...

Using vendor/rapidwebltd/php-google-oauth-2-handler/src/setup.php, I created a login with a type of Webserver. Because my project is a PHP project. Within the steps I don't know what the redirect URI is and I think I'm missing the refresh token.

Is there a way you anyone can help me figuring this out? Searched the internet therefor, but I'm getting more confused. 

![error google uri](https://user-images.githubusercontent.com/46164497/50450265-1ad73300-092d-11e9-8568-db1a5a6eb954.png)

Thanks in Advance!

**Comment by Monsieux** [comment]
I think I made it work, after manually creating a clientid. Very weird tho.
Fantastic project!

**Comment by hasnatbabur** [comment]
If you choose application type to "Other" then problem is solved!

**Comment by ajinkyakolhe** [comment]
> If you choose application type to "Other" then problem is solved!

This works perfect. I have been trying to resolve this for so long!

**Comment by QuesnelJ** [comment]
> If you choose application type to "Other" then problem is solved!

hasnatbabur dude, you are a life saver. I've been working on this for dayS, and your solution made it work. Thank you ever soooooo much.
