### ISSUE TITLE
$people->all() does not give me all contacts

### ISSUE THREAD

**Issue by Skeltzer** [rapidwebltd/php-google-people-api#24]
I have a Google account with 4704 contacts (according to the Google Contacts app). When looping through `$people->all()` I get only 4608 contacts. When I try to retrieve some of the missing contacts with `$people->get($resourceName)` the contacts do turn up (I can get the resourceName of a missing contact manually by inspecting the popup window on the Google Contacts page).

What is wrong? Why don't my 100 or so missing contacts show up?

**Comment by QuesnelJ** [comment]
I am experiencing similar issues. Have you resolved your issue?

**Comment by Skeltzer** [comment]
> I am experiencing similar issues. Have you resolved your issue?

No, but I'm not sure if it's Rapidweb's fault. I've done some TCP dumps while retrieving "all" records and I believe I simply don't always get all contacts, though why not is a mystery. I have rewritten my software to simply not expect to get all contacts all the time (i.e., to not consider missing contacts as "deleted").
