### ISSUE TITLE
Undefined variable: googleOAuth2Handler

### ISSUE THREAD

**Issue by henrymbuguak** [rapidwebltd/php-google-people-api#5]
I am trying to use this package in Laravel project.

I have imported this class
use RapidWeb\GooglePeopleAPI\GooglePeople;

When use this line in my code:

$client = new GooglePeople($googleOAuth2Handler);

When  passing $googleOAuth2Handle I get an error of Undefined variable

**Comment by Jord-JD** [comment]
You need to create the `$googleOAuth2Handler` object first. Make sure you go through the 'Setup' section of the readme.

**Comment by henrymbuguak** [comment]
Hello DivineOmega, I went through the setup process successful, I have also gone through the readme file but still getting the same error.

**Comment by Jord-JD** [comment]
Did you copy the code snippet that the setup script gives you?

**Comment by henrymbuguak** [comment]
Yes I did and also pasted auth code given by google.

**Comment by dizid** [comment]
Add this: use RapidWeb\GoogleOAuth2Handler\GoogleOAuth2Handler;
solves it.

**Comment by henrymbuguak** [comment]
@dizid Thanks it works!

**Comment by Muneeb1998** [comment]
@dizid Hello, Can you help me?
**Code**
![image](https://user-images.githubusercontent.com/50280520/151839012-8befdb8f-2268-4a25-81a0-9125feb53913.png)
**Output**
![image](https://user-images.githubusercontent.com/50280520/151839262-87ae3510-b521-44a1-ac6e-11d312a08c75.png)
